<a href="https://colab.research.google.com/github/Kmvijaylakshmi/MapUp-Data-Assessment-F/blob/main/Submissions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

def generate_car_matrix(csv_file_path):
    """
    Creates a DataFrame for id combinations from a CSV file.

    Args:
        csv_file_path (str): Path to the CSV file containing 'id_1', 'id_2', and 'car' columns.

    Returns:
        pandas.DataFrame: Matrix generated with 'car' values,
                          where 'id_1' and 'id_2' are used as indices and columns respectively.
                          Diagonal values are set to 0.
    """
    # Read the CSV file into a DataFrame
    df = pd.read_csv(csv_file_path)
    df2 = df.fillna(0)


    # Create a pivot table with 'id_1' as index, 'id_2' as columns, and 'car' as values
    car_matrix = df.pivot(index='id_1', columns='id_2', values='car')

    # Fill diagonal values with 0
    np.fill_diagonal(car_matrix.values, 0)


    return car_matrix
    print(car_matrix)
# Example usage:
# Assuming your CSV file is named 'dataset-1.csv'
car_matrix = generate_car_matrix('/dataset-1.csv')
print(car_matrix)

id_2    801    802    803    804    805    806    807    808    809    821  \
id_1
801    0.00   2.80   6.00   7.70  11.70  13.40  16.90  19.60  21.00  23.52
802    2.80   0.00   3.40   5.20   9.20  10.90  14.30  17.10  18.50  20.92
803    6.00   3.40   0.00   2.00   6.00   7.70  11.10  13.90  15.30  17.72
804    7.70   5.20   2.00   0.00   4.40   6.10   9.50  12.30  13.70  16.12
805   11.70   9.20   6.00   4.40   0.00   2.00   5.40   8.20   9.60  12.02
806   13.40  10.90   7.70   6.10   2.00   0.00   3.80   6.60   8.00  10.42
807   16.90  14.30  11.10   9.50   5.40   3.80   0.00   2.90   4.30   6.82
808   19.60  17.10  13.90  12.30   8.20   6.60   2.90   0.00   1.70   4.12
809   21.00  18.50  15.30  13.70   9.60   8.00   4.30   1.70   0.00   2.92
821   23.52  20.92  17.72  16.12  12.02  10.42   6.82   4.12   2.92   0.00
822   24.67  22.07  18.87  17.27  13.17  11.57   7.97   5.27   4.07   1.80
823   26.53  23.93  20.73  19.13  15.03  13.43   9.83   7.13   5.93   3.67
824   27.92  25.32  22.12  20.52  16.42   7.80  11.22   8.52   7.32   5.06
825   29.08  26.48  23.28  21.68  17.58  15.98  12.38   9.68   8.48   6.22
826   30.87  28.27  25.07  23.47  19.37  17.77  14.17  11.47  10.27   8.01
827   32.53  29.93  26.73  25.13  21.03  19.43  15.83  13.13  11.93   9.43
829   36.32  33.72  30.52  28.92  24.82  23.22  19.62  16.92  15.72  13.26
830   38.27  35.67  32.47  30.87  26.77  25.17  21.57  18.87  17.67  15.17
831   39.24  36.64  33.44  31.84  27.74  26.14  22.54  19.84  18.64  16.15

id_2    822    823    824    825    826    827    829    830    831
id_1
801   24.67  26.53  27.92  29.08  30.87  32.53  36.32  38.27  39.24
802   22.07  23.93  25.32  26.48  28.27  29.93  33.72  35.67  36.64
803   18.87  20.73  22.12  23.28  25.07  26.73  30.52  32.47  33.44
804   17.27  19.13  20.52  21.68  23.47  25.13  28.92  30.87  31.84
805   13.17  15.03  16.42  17.58  19.37  21.03  24.82  26.77  27.74
806   11.57  13.43  14.82  15.98  17.77  19.43  23.22  25.17  26.14
807    7.97   9.83  11.22  12.38  14.17  15.83  19.62  21.57  22.54
808    5.27   7.13   8.52   9.68  11.47  13.13  16.92  18.87  19.84
809    4.07   5.93   7.32   8.48  10.27  11.93  15.72  17.67  18.64
821    1.80   3.67   5.06   6.22   8.01   9.43  13.26  15.17  16.15
822    0.00   2.21   3.60   4.76   6.55   8.00  11.81  13.74  14.68
823    2.21   0.00   1.79   2.94   4.74   6.15  10.00  11.89  12.87
824    3.60   1.79   0.00   1.71   3.50   4.92   8.77  10.66  11.64
825    4.76   2.94   1.71   0.00   2.20   3.65   7.46   9.35  10.33
826    6.55   4.74   3.50   2.20   0.00   2.05   5.81   7.71   8.69
827    8.00   6.15   4.92   3.65   2.05   0.00   4.14   6.06   7.04
829   11.81  10.00  21.40   7.46   5.81   4.14   0.00   2.38   3.36
830   13.74  11.89  10.66    NaN   7.71   6.06   2.38   0.00   1.39
831   14.68  12.87  11.64  10.33   8.69   7.04   3.36   1.39   0.00

In [8]:
import pandas as pd

def get_type_count(df):
    """
    Add a new categorical column 'car_type' based on values of the 'car' column.
    Calculate the count of occurrences for each 'car_type' category.
    Return the result as a dictionary, sorted alphabetically based on keys.

    Args:
        df (pandas.DataFrame): Input DataFrame with 'car' column.

    Returns:
        dict: Dictionary containing the count of occurrences for each 'car_type' category.
    """
    # Add a new categorical column 'car_type'
    df['car_type'] = pd.cut(df['car'], bins=[float('-inf'), 15, 25, float('inf')],
                            labels=['low', 'medium', 'high'], right=False)

    # Calculate the count of occurrences for each 'car_type' category
    type_count = df['car_type'].value_counts().to_dict()

    # Sort the dictionary alphabetically based on keys
    type_count = dict(sorted(type_count.items()))

    return type_count

# Example usage:
# Assuming df is your DataFrame from 'dataset-1.csv'
df = pd.read_csv('/dataset-1.csv')
result = get_type_count(df)
print(result)

{'high': 56, 'low': 196, 'medium': 89}

In [9]:
import pandas as pd

def get_bus_indexes(csv_file_path):
    """
    Identify and return the indices where 'bus' values are greater than twice the mean value.

    Args:
        csv_file_path (str): Path to the CSV file containing 'bus' column.

    Returns:
        list: List of indices where 'bus' values are greater than twice the mean.
    """
    # Read the CSV file into a DataFrame
    df = pd.read_csv('/dataset-1.csv')

    # Calculate the mean value of the 'bus' column
    bus_mean = df['bus'].mean()

    # Identify indices where 'bus' values are greater than twice the mean
    bus_indexes = df[df['bus'] > 2 * bus_mean].index.tolist()

    # Sort the indices in ascending order
    bus_indexes.sort()

    return bus_indexes

# Example usage:
# Assuming your CSV file is named 'dataset-1.csv'
result = get_bus_indexes('dataset-1.csv')
print(result)

[2, 7, 12, 17, 25, 30, 54, 64, 70, 97, 144, 145, 149, 154, 160, 201, 206, 210, 215, 234, 235, 245, 250, 309, 314, 319, 322, 323, 334, 340]

In [10]:
import pandas as pd

def filter_routes(csv_file_path):
    """
    Return the sorted list of values in the 'route' column for which the average of 'truck' values is greater than 7.

    Args:
        csv_file_path (str): Path to the CSV file containing 'route' and 'truck' columns.

    Returns:
        list: Sorted list of values in the 'route' column.
    """
    # Read the CSV file into a DataFrame
    df = pd.read_csv('/dataset-1.csv')

    # Calculate the average of 'truck' values for each 'route'
    route_avg_truck = df.groupby('route')['truck'].mean()

    # Filter routes where the average of 'truck' values is greater than 7
    filtered_routes = route_avg_truck[route_avg_truck > 7].index.tolist()

    # Sort the list of routes in ascending order
    filtered_routes.sort()

    return filtered_routes

# Example usage:
# Assuming your CSV file is named 'dataset-1.csv'
result = filter_routes('dataset-1.csv')
print(result)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
import pandas as pd

def multiply_matrix(car_matrix):
    """
    Modify values in the DataFrame based on the specified logic.

    Args:
        car_matrix (pandas.DataFrame): Input DataFrame.

    Returns:
        pandas.DataFrame: Modified DataFrame with values rounded to 1 decimal place.
    """
    # Create a copy of the input DataFrame to avoid modifying the original
    modified_matrix = car_matrix.copy()

    # Apply the specified logic to modify values
    modified_matrix[modified_matrix > 20] *= 0.75
    modified_matrix[modified_matrix <= 20] *= 1.25

    # Round values to 1 decimal place
    modified_matrix = modified_matrix.round(1)

    return modified_matrix

# Example usage:
# Assuming you have the DataFrame 'car_matrix' from Question 1
modified_result = multiply_matrix(car_matrix)
print(modified_result)

id_2   801   802   803   804   805   806   807   808   809   821   822   823  \
id_1
801    0.0   3.5   7.5   9.6  14.6  16.8  21.1  24.5  19.7  22.0  23.1  24.9
802    3.5   0.0   4.2   6.5  11.5  13.6  17.9  21.4  23.1  19.6  20.7  22.4
803    7.5   4.2   0.0   2.5   7.5   9.6  13.9  17.4  19.1  22.2  23.6  19.4
804    9.6   6.5   2.5   0.0   5.5   7.6  11.9  15.4  17.1  20.2  21.6  23.9
805   14.6  11.5   7.5   5.5   0.0   2.5   6.8  10.2  12.0  15.0  16.5  18.8
806   16.8  13.6   9.6   7.6   2.5   0.0   4.8   8.2  10.0  13.0  14.5  16.8
807   21.1  17.9  13.9  11.9   6.8   4.8   0.0   3.6   5.4   8.5  10.0  12.3
808   24.5  21.4  17.4  15.4  10.2   8.2   3.6   0.0   2.1   5.2   6.6   8.9
809   19.7  23.1  19.1  17.1  12.0  10.0   5.4   2.1   0.0   3.6   5.1   7.4
821   22.0  19.6  22.2  20.2  15.0  13.0   8.5   5.2   3.6   0.0   2.2   4.6
822   23.1  20.7  23.6  21.6  16.5  14.5  10.0   6.6   5.1   2.2   0.0   2.8
823   24.9  22.4  19.4  23.9  18.8  16.8  12.3   8.9   7.4   4.6   2.8   0.0
824   20.9  23.7  20.7  19.2  20.5   9.8  14.0  10.6   9.2   6.3   4.5   2.2
825   21.8  24.8  21.8  20.3  22.0  20.0  15.5  12.1  10.6   7.8   5.9   3.7
826   23.2  21.2  23.5  22.0  24.2  22.2  17.7  14.3  12.8  10.0   8.2   5.9
827   24.4  22.4  20.0  23.6  19.7  24.3  19.8  16.4  14.9  11.8  10.0   7.7
829   27.2  25.3  22.9  21.7  23.3  21.8  24.5  21.2  19.7  16.6  14.8  12.5
830   28.7  26.8  24.4  23.2  20.1  23.6  20.2  23.6  22.1  19.0  17.2  14.9
831   29.4  27.5  25.1  23.9  20.8  24.5  21.1  24.8  23.3  20.2  18.4  16.1

id_2   824   825   826   827   829   830   831
id_1
801   20.9  21.8  23.2  24.4  27.2  28.7  29.4
802   23.7  24.8  21.2  22.4  25.3  26.8  27.5
803   20.7  21.8  23.5  20.0  22.9  24.4  25.1
804   19.2  20.3  22.0  23.6  21.7  23.2  23.9
805   20.5  22.0  24.2  19.7  23.3  20.1  20.8
806   18.5  20.0  22.2  24.3  21.8  23.6  24.5
807   14.0  15.5  17.7  19.8  24.5  20.2  21.1
808   10.6  12.1  14.3  16.4  21.2  23.6  24.8
809    9.2  10.6  12.8  14.9  19.7  22.1  23.3
821    6.3   7.8  10.0  11.8  16.6  19.0  20.2
822    4.5   5.9   8.2  10.0  14.8  17.2  18.4
823    2.2   3.7   5.9   7.7  12.5  14.9  16.1
824    0.0   2.1   4.4   6.2  11.0  13.3  14.6
825    2.1   0.0   2.8   4.6   9.3  11.7  12.9
826    4.4   2.8   0.0   2.6   7.3   9.6  10.9
827    6.2   4.6   2.6   0.0   5.2   7.6   8.8
829   20.1   9.3   7.3   5.2   0.0   3.0   4.2
830   13.3   NaN   9.6   7.6   3.0   0.0   1.7
831   14.6  12.9  10.9   8.8   4.2   1.7   0.0

In [12]:
import pandas as pd

def check_timestamp_completeness(df):
    # Convert start and end timestamps to datetime objects
    df['start_timestamp'] = pd.to_datetime(df['startDay'] + ' ' + df['startTime'],errors='coerce')
    df['end_timestamp'] = pd.to_datetime(df['endDay'] + ' ' + df['endTime'],errors='coerce')

    # Extract day of the week and hour from start and end timestamps
    df['start_day_of_week'] = df['start_timestamp'].dt.dayofweek
    df['end_day_of_week'] = df['end_timestamp'].dt.dayofweek
    df['start_hour'] = df['start_timestamp'].dt.hour
    df['end_hour'] = df['end_timestamp'].dt.hour

    # Group by (id, id_2)
    grouped = df.groupby(['id', 'id_2'])

    # Check completeness for each group
    completeness = grouped.apply(lambda group: check_group_completeness(group))

    return completeness

def check_group_completeness(group):
    # Check if the start timestamps cover a full 24-hour period
    start_hour_coverage = set(group['start_hour'])
    full_start_hour_coverage = set(range(24)) == start_hour_coverage

    # Check if the end timestamps cover a full 24-hour period
    end_hour_coverage = set(group['end_hour'])
    full_end_hour_coverage = set(range(24)) == end_hour_coverage
     # Check if the start timestamps span all 7 days of the week
    start_day_of_week_coverage = set(group['start_day_of_week'])
    full_start_day_of_week_coverage = set(range(7)) == start_day_of_week_coverage

    # Check if the end timestamps span all 7 days of the week
    end_day_of_week_coverage = set(group['end_day_of_week'])
    full_end_day_of_week_coverage = set(range(7)) == end_day_of_week_coverage

    # Return True if all conditions are satisfied, indicating completeness
    return (
        full_start_hour_coverage and full_end_hour_coverage and
        full_start_day_of_week_coverage and full_end_day_of_week_coverage
    )

# Example usage:
csv_file_path = '/dataset-2.csv'
df = pd.read_csv(csv_file_path)

completeness_series = check_timestamp_completeness(df)
print(completeness_series)

id       id_2
1014000  -1          False
1014002  -1          False
1014003  -1          False
1030000  -1          False
          1030002    False
                     ...
1330016   1330006    False
          1330008    False
          1330010    False
          1330012    False
          1330014    False
Length: 9254, dtype: bool

In [13]:
import pandas as pd
import networkx as nx


def calculate_distance_matrix(csv_file_path):
    # Read the CSV file into a DataFrame
    df = pd.read_csv(csv_file_path)

    # Create a directed graph to represent the toll locations and distances
    G = nx.DiGraph()

    # Add edges and their weights to the graph
    for index, row in df.iterrows():
        G.add_edge(row['id_start'], row['id_end'], weight=row['distance'])
        G.add_edge(row['id_end'], row['id_start'], weight=row['distance'])  # Bidirectional

    # Calculate the shortest path lengths between all pairs of nodes
    all_pairs_shortest_paths = dict(nx.all_pairs_dijkstra_path_length(G))

    # Create a DataFrame to store the distance matrix
    columns = sorted(list(set(df['id_start'].unique()) | set(df['id_end'].unique())))
    distance_matrix = pd.DataFrame(index=columns, columns=columns)

    # Populate the distance matrix with cumulative distances along known routes
    for source in columns:
        for destination in columns:
            if source == destination:
                distance_matrix.loc[source, destination] = 0
            else:
                try:
                    distance_matrix.loc[source, destination] = all_pairs_shortest_paths[source].get(destination, float('inf'))
                except KeyError:
                   # Handle the case where there is no known route between source and destination
                    distance_matrix.loc[source, destination] = float('inf')

    # Ensure the matrix is symmetric
    for i in range(len(columns)):
        for j in range(i + 1, len(columns)):
            distance_matrix.iloc[i, j] = distance_matrix.iloc[j, i]

    return distance_matrix

csv_file_path = '/dataset-3.csv'
resulting_distance_matrix = calculate_distance_matrix(csv_file_path)
print(resulting_distance_matrix)

        1001400 1001402 1001404 1001406 1001408 1001410 1001412 1001414  \
1001400       0     9.7    29.9    45.9    67.6    78.7    94.3   112.5
1001402     9.7       0    20.2    36.2    57.9    69.0    84.6   102.8
1001404    29.9    20.2       0    16.0    37.7    48.8    64.4    82.6
1001406    45.9    36.2    16.0       0    21.7    32.8    48.4    66.6
1001408    67.6    57.9    37.7    21.7       0    11.1    26.7    44.9
1001410    78.7    69.0    48.8    32.8    11.1       0    15.6    33.8
1001412    94.3    84.6    64.4    48.4    26.7    15.6       0    18.2
1001414   112.5   102.8    82.6    66.6    44.9    33.8    18.2       0
1001416   125.7   116.0    95.8    79.8    58.1    47.0    31.4    13.2
1001418   139.3   129.6   109.4    93.4    71.7    60.6    45.0    26.8
1001420   152.2   142.5   122.3   106.3    84.6    73.5    57.9    39.7
1001422   161.8   152.1   131.9   115.9    94.2    83.1    67.5    49.3
1001424   173.2   163.5   143.3   127.3   105.6    94.5    78.9    60.7
1001426   191.8   182.1   161.9   145.9   124.2   113.1    97.5    79.3
1001428   207.6   197.9   177.7   161.7   140.0   128.9   113.3    95.1
1001430   216.2   206.5   186.3   170.3   148.6   137.5   121.9   103.7
1001432   225.2   215.5   195.3   179.3   157.6   146.5   130.9   112.7
1001434   233.1   223.4   203.2   187.2   165.5   154.4   138.8   120.6
1001436   237.1   227.4   207.2   191.2   169.5   158.4   142.8   124.6
1001437   242.1   232.4   212.2   196.2   174.5   163.4   147.8   129.6
1001438   246.1   236.4   216.2   200.2   178.5   167.4   151.8   133.6
1001440   256.1   246.4   226.2   210.2   188.5   177.4   161.8   143.6
1001442   260.0   250.3   230.1   214.1   192.4   181.3   165.7   147.5
1001444   273.2   263.5   243.3   227.3   205.6   194.5   178.9   160.7
1001446   279.8   270.1   249.9   233.9   212.2   201.1   185.5   167.3
1001448   289.4   279.7   259.5   243.5   221.8   210.7   195.1   176.9
1001450   305.1   295.4   275.2   259.2   237.5   226.4   210.8   192.6
1001452   315.0   305.3   285.1   269.1   247.4   236.3   220.7   202.5
1001454   326.3   316.6   296.4   280.4   258.7   247.6   232.0   213.8
1001456   339.9   330.2   310.0   294.0   272.3   261.2   245.6   227.4
1001458   348.8   339.1   318.9   302.9   281.2   270.1   254.5   236.3
1001460   353.9   344.2   324.0   308.0   286.3   275.2   259.6   241.4
1001461   366.7   357.0   336.8   320.8   299.1   288.0   272.4   254.2
1001462   371.8   362.1   341.9   325.9   304.2   293.1   277.5   259.3
1001464   398.5   388.8   368.6   352.6   330.9   319.8   304.2   286.0
1001466   407.0   397.3   377.1   361.1   339.4   328.3   312.7   294.5
1001468   417.7   408.0   387.8   371.8   350.1   339.0   323.4   305.2
1001470   428.3   418.6   398.4   382.4   360.7   349.6   334.0   315.8
1001472   444.3   434.6   414.4   398.4   376.7   365.6   350.0   331.8
1001488   264.5   254.8   234.6   218.6   196.9   185.8   170.2   152.0
1004354   270.5   260.8   240.6   224.6   202.9   191.8   176.2   158.0
1004355   272.5   262.8   242.6   226.6   204.9   193.8   178.2   160.0
1004356   268.5   258.8   238.6   222.6   200.9   189.8   174.2   156.0

        1001416 1001418  ... 1001462 1001464 1001466 1001468 1001470 1001472  \
1001400   125.7   139.3  ...   371.8   398.5   407.0   417.7   428.3   444.3
1001402   116.0   129.6  ...   362.1   388.8   397.3   408.0   418.6   434.6
1001404    95.8   109.4  ...   341.9   368.6   377.1   387.8   398.4   414.4
1001406    79.8    93.4  ...   325.9   352.6   361.1   371.8   382.4   398.4
1001408    58.1    71.7  ...   304.2   330.9   339.4   350.1   360.7   376.7
1001410    47.0    60.6  ...   293.1   319.8   328.3   339.0   349.6   365.6
1001412    31.4    45.0  ...   277.5   304.2   312.7   323.4   334.0   350.0
1001414    13.2    26.8  ...   259.3   286.0   294.5   305.2   315.8   331.8
1001416       0    13.6  ...   246.1   272.8   281.3   292.0   302.6   318.6
1001418    13.6       0  ...   232.5   259.2   267.7   278.4   289.0   305.0
1001420    26.5    12.9  ...   219.6   246.3   254.8   265.5   276.1   292.1
1001422    36.1    22.5  ...   210.0   236.7   245.2   255.9   266.5   282.5
1001424    47.5    33.9  ...   198.6   225.3   233.8   244.5   255.1   271.1
1001426    66.1    52.5  ...   180.0   206.7   215.2   225.9   236.5   252.5
1001428    81.9    68.3  ...   164.2   190.9   199.4   210.1   220.7   236.7
1001430    90.5    76.9  ...   155.6   182.3   190.8   201.5   212.1   228.1
1001432    99.5    85.9  ...   146.6   173.3   181.8   192.5   203.1   219.1
1001434   107.4    93.8  ...   138.7   165.4   173.9   184.6   195.2   211.2
1001436   111.4    97.8  ...   134.7   161.4   169.9   180.6   191.2   207.2
1001437   116.4   102.8  ...   129.7   156.4   164.9   175.6   186.2   202.2
1001438   120.4   106.8  ...   125.7   152.4   160.9   171.6   182.2   198.2
1001440   130.4   116.8  ...   115.7   142.4   150.9   161.6   172.2   188.2
1001442   134.3   120.7  ...   111.8   138.5   147.0   157.7   168.3   184.3
1001444   147.5   133.9  ...    98.6   125.3   133.8   144.5   155.1   171.1
1001446   154.1   140.5  ...    92.0   118.7   127.2   137.9   148.5   164.5
1001448   163.7   150.1  ...    82.4   109.1   117.6   128.3   138.9   154.9
1001450   179.4   165.8  ...    66.7    93.4   101.9   112.6   123.2   139.2
1001452   189.3   175.7  ...    56.8    83.5    92.0   102.7   113.3   129.3
1001454   200.6   187.0  ...    45.5    72.2    80.7    91.4   102.0   118.0
1001456   214.2   200.6  ...    31.9    58.6    67.1    77.8    88.4   104.4
1001458   223.1   209.5  ...    23.0    49.7    58.2    68.9    79.5    95.5
1001460   228.2   214.6  ...    17.9    44.6    53.1    63.8    74.4    90.4
1001461   241.0   227.4  ...     5.1    31.8    40.3    51.0    61.6    77.6
1001462   246.1   232.5  ...       0    26.7    35.2    45.9    56.5    72.5
1001464   272.8   259.2  ...    26.7       0     8.5    19.2    29.8    45.8
1001466   281.3   267.7  ...    35.2     8.5       0    10.7    21.3    37.3
1001468   292.0   278.4  ...    45.9    19.2    10.7       0    10.6    26.6
1001470   302.6   289.0  ...    56.5    29.8    21.3    10.6       0    16.0
1001472   318.6   305.0  ...    72.5    45.8    37.3    26.6    16.0       0
1001488   138.8   125.2  ...   107.3   134.0   142.5   153.2   163.8   179.8
1004354   144.8   131.2  ...   101.3   128.0   136.5   147.2   157.8   173.8
1004355   146.8   133.2  ...    99.3   126.0   134.5   145.2   155.8   171.8
1004356   142.8   129.2  ...   103.3   130.0   138.5   149.2   159.8   175.8

        1001488 1004354 1004355 1004356
1001400   264.5   270.5   272.5   268.5
1001402   254.8   260.8   262.8   258.8
1001404   234.6   240.6   242.6   238.6
1001406   218.6   224.6   226.6   222.6
1001408   196.9   202.9   204.9   200.9
1001410   185.8   191.8   193.8   189.8
1001412   170.2   176.2   178.2   174.2
1001414   152.0   158.0   160.0   156.0
1001416   138.8   144.8   146.8   142.8
1001418   125.2   131.2   133.2   129.2
1001420   112.3   118.3   120.3   116.3
1001422   102.7   108.7   110.7   106.7
1001424    91.3    97.3    99.3    95.3
1001426    72.7    78.7    80.7    76.7
1001428    56.9    62.9    64.9    60.9
1001430    48.3    54.3    56.3    52.3
1001432    39.3    45.3    47.3    43.3
1001434    31.4    37.4    39.4    35.4
1001436    27.4    33.4    35.4    31.4
1001437    22.4    28.4    30.4    26.4
1001438    18.4    24.4    26.4    22.4
1001440     8.4    14.4    16.4    12.4
1001442     4.5    10.5    12.5     8.5
1001444     8.7     2.7     0.7     4.7
1001446    15.3     9.3     7.3    11.3
1001448    24.9    18.9    16.9    20.9
1001450    40.6    34.6    32.6    36.6
1001452    50.5    44.5    42.5    46.5
1001454    61.8    55.8    53.8    57.8
1001456    75.4    69.4    67.4    71.4
1001458    84.3    78.3    76.3    80.3
1001460    89.4    83.4    81.4    85.4
1001461   102.2    96.2    94.2    98.2
1001462   107.3   101.3    99.3   103.3
1001464   134.0   128.0   126.0   130.0
1001466   142.5   136.5   134.5   138.5
1001468   153.2   147.2   145.2   149.2
1001470   163.8   157.8   155.8   159.8
1001472   179.8   173.8   171.8   175.8
1001488       0     6.0     8.0     4.0
1004354     6.0       0     2.0     2.0
1004355     8.0     2.0       0     4.0
1004356     4.0     2.0     4.0       0

[43 rows x 43 columns]

In [25]:
import pandas as pd

def unroll_distance_matrix(df):
    """
    Unroll a distance matrix DataFrame into a DataFrame with id_start, id_end, and distance columns.

    Args:
        df (pd.DataFrame): Input DataFrame representing distances between IDs.

    Returns:
        pd.DataFrame: DataFrame with three columns: id_start, id_end, and distance.
    """
    # Create a copy of the input DataFrame
    unrolled_df = df.copy()

    # Reset index to turn the 'id' column into a regular column
    unrolled_df.reset_index(inplace=True)

    # Melt the DataFrame to unpivot the matrix
    unrolled_df = pd.melt(unrolled_df, id_vars=['index'], var_name='id_end', value_name='distance')

    # Rename columns to match the desired output
    unrolled_df.columns = ['id_start', 'id_end', 'distance']

    # Exclude rows where id_start is equal to id_end
    unrolled_df = unrolled_df[unrolled_df['id_start'] != unrolled_df['id_end']]

    unrolled_df['id_start'], unrolled_df['id_end'] = unrolled_df['id_end'], unrolled_df['id_start']

    # Reset index for the final DataFrame
    unrolled_df.reset_index(drop=True, inplace=True)

    return unrolled_df

# Example usage:
# Assuming your DataFrame is named 'distance_matrix'
result = unroll_distance_matrix(resulting_distance_matrix)
print(result)

     id_start   id_end distance
0     1001400  1001402      9.7
1     1001400  1001404     29.9
2     1001400  1001406     45.9
3     1001400  1001408     67.6
4     1001400  1001410     78.7
...       ...      ...      ...
1801  1004356  1001470    159.8
1802  1004356  1001472    175.8
1803  1004356  1001488      4.0
1804  1004356  1004354      2.0
1805  1004356  1004355      4.0

[1806 rows x 3 columns]

In [26]:
import pandas as pd

def find_ids_within_ten_percentage_threshold(df, reference_value):
    """
    Find and return a sorted list of values from the id_start column within 10% threshold of the reference value's average.

    Args:
        df (pd.DataFrame): Input DataFrame with columns id_start, id_end, and distance.
        reference_value (int): Reference value from the id_start column.

    Returns:
        list: Sorted list of values from the id_start column within 10% threshold of the reference value's average.
    """
    # Filter rows where id_start is the reference value
    reference_rows = df[df['id_start'] == reference_value]

    # Calculate the average distance for the reference value
    reference_average = reference_rows['distance'].mean()

    # Calculate the lower and upper thresholds within 10% of the reference average
    lower_threshold = reference_average - 0.1 * reference_average
    upper_threshold = reference_average + 0.1 * reference_average

    # Filter rows where id_start is within the threshold range
    within_threshold = df[(df['distance'] >= lower_threshold) & (df['distance'] <= upper_threshold)]

    # Get unique values from the id_start column and sort the list
    result1 = sorted(within_threshold['id_start'].unique())

    return result1

# Example usage:
# Assuming your DataFrame is named 'unrolled_df' and reference_value is 123 (replace with your actual reference value)
result1 = find_ids_within_ten_percentage_threshold(result, reference_value=123)
print(result1)

[]

In [28]:
import pandas as pd

def calculate_toll_rate(df):
    """
    Calculate toll rates for each vehicle type based on distance and rate coefficients.

    Args:
        df (pd.DataFrame): Input DataFrame with columns id_start, id_end, distance.

    Returns:
        pd.DataFrame: DataFrame with toll rates for each vehicle type added as columns.
    """
    # Copy the input DataFrame to avoid modifying the original
    result_df = df.copy()

    # Define rate coefficients for each vehicle type
    rate_coefficients = {'moto': 0.8, 'car': 1.2, 'rv': 1.5, 'bus': 2.2, 'truck': 3.6}

    # Calculate toll rates for each vehicle type
    for vehicle_type, rate_coefficient in rate_coefficients.items():
        result_df[vehicle_type] = result_df['distance'] * rate_coefficient

    # Drop the 'distance' column from the result DataFrame
    result_df = result_df.drop(columns=['distance'])

    return result_df

# Example usage:
# Assuming your DataFrame is named 'unrolled_df'
result_with_toll = calculate_toll_rate(result)
print(result_with_toll)

     id_start   id_end    moto     car      rv     bus   truck
0     1001400  1001402    7.76   11.64   14.55   21.34   34.92
1     1001400  1001404   23.92   35.88   44.85   65.78  107.64
2     1001400  1001406   36.72   55.08   68.85  100.98  165.24
3     1001400  1001408   54.08   81.12   101.4  148.72  243.36
4     1001400  1001410   62.96   94.44  118.05  173.14  283.32
...       ...      ...     ...     ...     ...     ...     ...
1801  1004356  1001470  127.84  191.76   239.7  351.56  575.28
1802  1004356  1001472  140.64  210.96   263.7  386.76  632.88
1803  1004356  1001488     3.2     4.8     6.0     8.8    14.4
1804  1004356  1004354     1.6     2.4     3.0     4.4     7.2
1805  1004356  1004355     3.2     4.8     6.0     8.8    14.4

[1806 rows x 7 columns]

In [49]:
import pandas as pd
import numpy as np
from datetime import time

def calculate_time_based_toll_rates(df):
    """
    Calculate time-based toll rates and add the results as columns to the DataFrame.

    Args:
        df (pd.DataFrame): Input DataFrame with columns id_start, id_end, distance, startDay, startTime, endDay, and endTime.

    Returns:
        pd.DataFrame: DataFrame with added columns for time-based toll rates.
    """
    # Create a copy of the input DataFrame
    result_df = df.copy()

    # Define time ranges and discount factors
    time_ranges = [
        {'start': time(0, 0, 0), 'end': time(10, 0, 0), 'weekday_factor': 0.8, 'weekend_factor': 0.7},
        {'start': time(10, 0, 1), 'end': time(18, 0, 0), 'weekday_factor': 1.2, 'weekend_factor': 0.7},
        {'start': time(18, 0, 1), 'end': time(23, 59, 59), 'weekday_factor': 0.8, 'weekend_factor': 0.7}
    ]

    # Convert start_time and end_time to datetime.time type
    result_df['start_time'] = pd.to_datetime(result_df['startTime']).dt.time
    result_df['end_time'] = pd.to_datetime(result_df['endTime']).dt.time

    # Create a function to calculate the discount factor based on time range
    def calculate_discount_factor(row):
        for time_range in time_ranges:
            if time_range['start'] <= row['start_time'] <= time_range['end']:
                return time_range['weekday_factor'] if row['startDay'] < 'Saturday' else time_range['weekend_factor']

    # Apply the discount factor to each row
    result_df['discount_factor'] = result_df.apply(calculate_discount_factor, axis=1)

    # Apply the discount factor to each vehicle type column
    vehicle_columns = ['moto_toll', 'car_toll', 'rv_toll', 'bus_toll', 'truck_toll']
    for column in vehicle_columns:
        result_df[column] *= result_df['discount_factor']

    # Drop intermediate columns used for calculations
    result_df.drop(['start_time', 'end_time', 'discount_factor'], axis=1, inplace=True)

    return result_df

# Example usage:
# Assuming your DataFrame is named 'result_with_toll'
result_with_time_based_toll = calculate_time_based_toll_rates(result1)
print(result_with_time_based_toll)

TypeError: ignored